sudo: false
language: node_js
node_js:
- stable
script:
- npm run setup
- npm run build
deploy:
  provider: npm
  email: mareklani@outlook.com
  on:
    tags: true
  api_key:
    secure: kT3GBGkc80cKqVGBHIgxucKoPlGPQ1l9TL507AU6Y2VJZ1MgA9L1f1UPK/+O8vwAOkL1L2YUwOzzjAxYBzq4gbhwJsUUdfQBofT2NcSCbAm36IsBUkbuayVbpsWaCq1qnWSw8Ic2IBkDQuyoUNBFnlTD2RQF8JIKGYgWJDDzRtlCjdJnyWHJPSnQyyQC/ceMgkF3xILVckQ20mEzI1XRck0dU0QBcfToAfB4HG9WwjKqwNvjzcuWez6i4oMH5Q+O0LhyM2Gkd59Rg2v/WUx6BV5zu0fqtkGSB0azao32xkCFxIWh0EblaXuxJwzADSgdjS1s9K/EmA/nlPTQ8QGqkNP1k+1LrImot6OTRFcLLcT7jk49/pBj8fJ+PekPWJh2WQ7YSlqVmqXrngYpML9AkFqj92NP6D7HcTBkbM8bXy2yTlzKxZkuBWieQdiNnz3puTl1ursWqfkxt8xyfwh4vRsptimJyPJyCJACpzOwkEi/sllqJw1BBtBtlhZlu56lXwdcR1hgrBQubw+EjbrPuuks5f2gYCxKTfC8b4zqncyYYrtlJ41ZyMxm5YwOq6s8E6Pmcu07gl+EOg+36ApHVOMD2X/GNQo8hzO/QfpCcYZoeRvHr53KTdTQPJtL/HXDsG5uHV0cgHA7Wbux3uoX+qxZxyLankLCKUsoAi/rWkc=
